@baseUrl = http://localhost:8080

# Create JWT
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "secure"
}

###
@authToken = {{login.response.body.$.token}}

###

# Get status
GET {{baseUrl}}/auth
Authorization: Bearer {{authToken}}

###

# Logout
GET {{baseUrl}}/auth/logout
Authorization: Bearer {{authToken}}}

