@baseUrl = http://localhost:8080

# Create JWT
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "secure"
}

###
@authToken = {{login.response.body.$.token}}


# Create Person
POST {{baseUrl}}/people
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Josué López"
}

###
# Get Person
GET {{baseUrl}}/people/josuelopez
Authorization: Bearer {{authToken}}

###
# Get people
GET {{baseUrl}}/people?limit=1&skip=1
Authorization: Bearer {{authToken}}

###
# Get category
GET {{baseUrl}}/people/category?name=zone
Authorization: Bearer {{authToken}}

###
# Query people
GET {{baseUrl}}/people/search?name=abi
Authorization: Bearer {{authToken}}


###
# Update Person
PUT {{baseUrl}}/people
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "personId": "josuelopez",
  "registered": false
}

###

# Delete Person
DELETE {{baseUrl}}/people/josuelopez
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

# Get stats
GET {{baseUrl}}/people/stats?accessed=1
Authorization: Bearer {{authToken}}
