@baseUrl = http://localhost:3000

# Create Person
POST {{baseUrl}}/people
Content-Type: application/json

{
  "name": "Josué López"
}

###
# Get Person
GET {{baseUrl}}/people/josuelopez

###
# Update Person
PUT {{baseUrl}}/people
Content-Type: application/json

{
  "personId": "josuelopez",
  "registered": false
}

###

# Delete Person
DELETE {{baseUrl}}/people/josuelopez
Content-Type: application/json
