@baseUrl = http://localhost:3000

# Create Admin User
POST {{baseUrl}}/user
Content-Type: application/json

{
  "username": "gerardoisai",
  "name": "Gerardo Diaz",
  "role": "admin",
  "password": "p@55word"
}

###
# Read User
GET {{baseUrl}}/user/gerardoisai


###
# Update user
PUT {{baseUrl}}/user
Content-Type: application/json

{
  "username": "gerardoisai",
  "name": "Gerardo Isai Diaz",
  "role": "operator"
}

###
# Delete User
DELETE {{baseUrl}}/user/gerardoisai

###
# Create Operator User
POST {{baseUrl}}/user
Content-Type: application/json

{
  "username": "msilverio",
  "name": "Martin Silverio",
  "role": "operator",
  "password": "p@55word"
}
