@baseUrl = http://localhost:8080

# Create operator user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "test",
  "name": "Test User",
  "role": "operator",
  "password": "secure"
}

# Create admin user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "testadmin",
  "name": "Test Admin",
  "role": "admin",
  "password": "secureadm"
}

###
# Create JWT
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "testadmin",
  "password": "secureadm"
}

###
@authToken = {{login.response.body.$.token}}

###
# Read User
GET {{baseUrl}}/users/gerardoisai
Authorization: Bearer {{authToken}}

###
# Read Users
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}

###
# Update user
PUT {{baseUrl}}/user
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "username": "gerardoisai",
  "name": "Gerardo Isai Diaz",
  "role": "operator"
}

###
# Delete User
DELETE {{baseUrl}}/users/gerardoisai
Authorization: Bearer {{authToken}}
